logger:
  levels:
    br.com.samueltorga: TRACE

KAFKA_BOOTSTRAP_SERVERS: localhost:9102,localhost:9096,localhost:9099

MONGO_DB_HOST: localhost:27017
MONGO_DB_USER: wikimedia_app_user
MONGO_DB_PASS: password

OPENSEARCH_HOST: http://localhost:9200